server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG

spring:
  cloud:
    gateway:
      routes:
        - id: backend
          uri: http://localhost:80
          predicates:
            - Path=/**
