server:
  port: 8080
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithm: HS256
security:
  signing-key: secret
  oauth2:
    authorization:
      token-key-access: permitAll()
      check-token-access: permitAll()
    client:
      client-id: demo-app
      client-secret: 8bb69f21-6965-41a1-b0e6-7907435d2ddd
