#
# Application
# ----------------------------------------------------------------------------
spring:
  application:
    name: tomcat
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

app:
  hello: hello-docker
