server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO

spring:
  cloud:
    gateway:
      routes:
        - id: backend
          uri: http://localhost:80
          predicates:
            - Path=/status/**
