#
# Application
# ----------------------------------------------------------------------------
spring:
  application:
    name: tomcat
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

#
# Embed Server
# ----------------------------------------------------------------------------
server:
  port: 8080
  forward-headers-strategy: native
  error:
    include-exception: false
    include-stacktrace: never
    include-message: always
    whitelabel:
      enabled: false

app:
  hello: hello
